### ISSUE TITLE
Leaves not working with pass through foliage

### ISSUE THREAD

**Issue by Aceplante** [x3rdev/FantasyTrees#1]
I would expect to fall through the leaves, yet I do not. It seems to work with every other mod Ive tried, except yours

Edit: also the leaves are minable by axe, and not hoe as I expected. Perhaps that has something to do with it?

**Comment by x3rdev** [comment]
Resolved in newest update.
https://github.com/x3rdev/FantasyTrees/commit/edff498d8257a0b7944c77d6a451685fa66028c3
