### ISSUE TITLE
Biome Cutoff

### ISSUE THREAD

**Issue by AusPakeha** [x3rdev/FantasyTrees#8]
During development of my modpack, i found several trees that have been cut flat on or near a biome edge.

Note: i am using William Wythers' Expanded Ecosphere

**Comment by AusPakeha** [comment]
![2024-02-10_13 33 09](https://github.com/x3rdev/FantasyTrees/assets/23236791/8f96e991-4f58-4616-be76-067a79c82422)

**Comment by x3rdev** [comment]
Yeah, this seems to be an issue with the port, I'm working on it, not sure when ill finish but this is an issue with the mod

**Comment by x3rdev** [comment]
fixed
